# Still needs tweaks so that a 'release' commit causes Gradle to
# execute the 'bintrayUpload' task instead of the 'build' task.
# Or maybe the upload should always happen, but the publishing
# is a separate task?
language: java
script: ./.travis/builder.sh
jdk:
- oraclejdk8

# Shamelessly copied from Jamz's TokenTool configuration file. :)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_deploy:
  - ./gradlew deploy
  - echo "Tag: $TRAVIS_TAG, Commit: $TRAVIS_COMMIT"
  - ls -l build/libs/
deploy:
  provider: releases
  api_key:
    secure: $DEPLOYMENT_KEY
  file_glob: true
# file: releases/release-*/bundles/*
  file: build/libs/*.jar
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  draft: true
  on:
    repo: Azhrei/rplib
    tags: true
    all_branches: true
